### ISSUE TITLE
Sites do not stay disabled

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#71]
High priority as web is pretty unusable with the plugin until this is fixed (continually having to press disable for the same web sites)

For example, visit nytimes.com, click 'disable for site', then return 20 minutes later, and content is blocked again

Also, what about the case where a search engine is blocked (eg Google) and one actually wants to whitelist the site, not the search... This doesn't seem to work, though it may just be the problem above

**Comment by cqx931** [comment]
I tried to reproduce it but after 30 minutes, I still don't see the case you mentioned above.
Is there any error message in the console?
Chrome version: 62.0.3202.89 (Official Build) (64-bit)

**Comment by dhowe** [comment]
strange -- perhaps just keep it enabled, and do your other work... then see if it pops up later in the day

**Comment by dhowe** [comment]
I see many cases of the following error (can we catch this?) in the console:

    extensions::messaging:79 Uncaught Error: Attempting to use a disconnected port object
        at PortImpl.postMessage (extensions::messaging:79:13)
        at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:149:26)
        at responseCallback (extensions::messaging:185:16)
        at Object.success (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/background.js:508:21)
        at i (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:2:27151)
        at Object.fireWith [as resolveWith] (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:2:27914)
        at z (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:4:12120)
        at XMLHttpRequest.<anonymous> (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:4:15680)
    PortImpl.postMessage @ extensions::messaging:79
    publicClassPrototype.(anonymous function) @ extensions::utils:149
    responseCallback @ extensions::messaging:185
    success @ background.js:508
    i @ jquery-2.2.3.js:2
    fireWith @ jquery-2.2.3.js:2
    z @ jquery-2.2.3.js:4
    (anonymous) @ jquery-2.2.3.js:4
    XMLHttpRequest.send (async)
    send @ jquery-2.2.3.js:4
    ajax @ jquery-2.2.3.js:4
    checkServer @ background.js:498
    checkPage @ background.js:561
    (anonymous) @ background.js:85
    (anonymous) @ background.js:298
    safeCallbackApply @ extensions::uncaught_exception_handler:27
    handleResponse @ extensions::sendRequest:67

------------------

    background.js:419 No tab with id: 178.

**Comment by dhowe** [comment]
Do you see endless versions of this error in your background console?

![image](https://user-images.githubusercontent.com/737638/32917979-cfcbd6b4-cb5b-11e7-952c-1044adfa1df7.png)

**Comment by cqx931** [comment]
Please see:
https://github.com/dhowe/ChinaEye/issues/25
