### ISSUE TITLE
Cannot disable for site

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#72]
https://www.google.com.hk/search?q=Shiu+Fai+Terrace&oq=Shiu+Fai+Terrace&aqs=chrome..69i57j0l5.181j0j7&sourceid=chrome&ie=UTF-8

![image](https://user-images.githubusercontent.com/737638/32425653-d1626a0c-c2ef-11e7-8616-e1db3c19db80.png)

**Comment by cqx931** [comment]
I can't reproduce this. I can disable ChinaEye on the page above.
Is there any error message?

**Comment by dhowe** [comment]
When I go this page, I am disabled, but cannot resume. 
With the following error (which recurs continually):

    Uncaught Error: Attempting to use a disconnected port object
        at PortImpl.postMessage (extensions::messaging:79:13)
        at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:149:26)
        at responseCallback (extensions::messaging:185:16)
        at Object.success (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/background.js:508:21)
        at i (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:2:27151)
        at Object.fireWith [as resolveWith] (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:2:27914)
        at z (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:4:12120)
        at XMLHttpRequest.<anonymous> (chrome-extension://kbkejkbhaiggcfnalkdlphlikillhlpf/js/jquery-2.2.3.js:4:15680)

**Comment by dhowe** [comment]
![screen shot 2017-11-11 at 2 44 32 am](https://user-images.githubusercontent.com/737638/32673464-47ed9b9a-c68a-11e7-92ff-e07f1667f863.png)

**Comment by dhowe** [comment]
closing for now
